### ISSUE TITLE
Thumbnails not load and io.UnsupportedOperation: seek

### ISSUE THREAD

**Issue by FinderX** [happypandax/happypandax#69]
**Describe the bug**
- The thumbnails are not loading or take like 5 minutes or more to load, when you browse the gallery or search / filter. This happens when too much content is requested quickly.

**To Reproduce**

1. Go to '...':
- Inbox or Library where is not empty.

2. Click on '....':
- Go or search anything that provoke the content is changed, quickly.

3. See error:
- On the server side:
>: Traceback (most recent call last):
>: File "site-packages/gevent/threadpool.py", line 211, in _worker
>: io.UnsupportedOperation: seek
>: Wed Oct 31 04:02:02 2018
>: (<ThreadPool at 0x7f9d202b4470 0/1/10>, <built-in method seek of ZipExtFile object at 0x7f9d106cf2e8>) failed with UnsupportedOperation

- On the client / browser:
The thumbnails are not loading or take like 5 minutes to load.

**Expected behavior**
- The thumbnails will load, at least faster than 5 minutes.

**Logs**
If applicable, include your ``error.log`` or ``debug.log`` found in ``[HPX]\logs\`` to help identifying your problem.
- Attached.
[activity.log](https://github.com/happypandax/happypandax/files/2533130/activity.log)
[error.log](https://github.com/happypandax/happypandax/files/2533131/error.log)
[plugin.log](https://github.com/happypandax/happypandax/files/2533132/plugin.log)

**Screenshots**
- N/A

**Environment:**
 - OS: Linux Mint 17.3
 - Browser: Vivaldi Stable version 2.0.1309.42 (Chromium based browser)
 - HPX Version: release-0.4.0

**Additional context**
- Not for the moment.

**Comment by twiddli** [comment]
Hello, can you please try and see if it still occurs in `0.5.0`?

**Comment by FinderX** [comment]
Still the same problem.
![screenshot from 2018-10-31 23-14-39](https://user-images.githubusercontent.com/8683793/47828761-2e1db600-dd63-11e8-8d34-8193418fd904.png)
After 5 the thumbnails were loaded.

**Comment by Evaia** [comment]
I actually receive this error repeatedly as well, however my thumbnails _do_ load regardless.
>: Wed Oct 31 22:46:31 2018
>: (<ThreadPool at 0xa2e7b50 0/1/10>, <built-in method seek of ZipExtFile object at 0x0B3490B0>) failed with UnsupportedOperation
>: Traceback (most recent call last):
>: File "env\lib\site-packages\gevent\threadpool.py", line 211, in _worker
>: io.UnsupportedOperation: seek
>: Wed Oct 31 22:46:31 2018
>: (<ThreadPool at 0xb01ccd0 0/1/10>, <built-in method seek of ZipExtFile object at 0x0B3E9510>) failed with UnsupportedOperation
>: Traceback (most recent call last):
>: File "env\lib\site-packages\gevent\threadpool.py", line 211, in _worker
>: io.UnsupportedOperation: seek
>: Wed Oct 31 22:46:32 2018
>: (<ThreadPool at 0x8520370 0/1/10>, <built-in method seek of ZipExtFile object at 0x0654A070>) failed with UnsupportedOperation
>: Traceback (most recent call last):
>: File "env\lib\site-packages\gevent\threadpool.py", line 211, in _worker
>: io.UnsupportedOperation: seek
>: Wed Oct 31 22:46:32 2018
>: (<ThreadPool at 0x84f3f10 0/1/10>, <built-in method seek of ZipExtFile object at 0x0A4DC990>) failed with UnsupportedOperation
>: Traceback (most recent call last):
>: File "env\lib\site-packages\gevent\threadpool.py", line 211, in _worker
>: io.UnsupportedOperation: seek
>: Wed Oct 31 22:46:33 2018
>: (<ThreadPool at 0x87d9610 0/1/10>, <built-in method seek of ZipExtFile object at 0x09371A30>) failed with UnsupportedOperation

**Comment by FinderX** [comment]
I need to clarify something.
I hurry to answer and do not let the images to load for the first time.
Now I do load everything and try doing several searches.
The thumbnails were loaded much faster this time.
I noticed that some thumbnails were loaded around 1 minute and after that they were generated before, I do not know if it is part of the expected result.

I think the problem is fixed.
I also leave the logs if they are interested.
[activity.log](https://github.com/happypandax/happypandax/files/2537195/activity.log)
[error.log](https://github.com/happypandax/happypandax/files/2537196/error.log)
[plugin.log](https://github.com/happypandax/happypandax/files/2537197/plugin.log)
[console-output.log](https://github.com/happypandax/happypandax/files/2537200/console-output.log)

[io.UnsupportedOperation: seek] errors still appear but the main problem is fixed.

**Comment by FinderX** [comment]
@twiddli Thank you.
I'm gonna close the thread.

**Comment by nonamethanks** [comment]
@twiddli I still get the error spam, could it be removed from the console? It drowns any other error.

**Comment by twiddli** [comment]
i'll look into it

**Comment by twiddli** [comment]
You can read the recent errors in the `error.log` file
